# Generated by Django 5.1.7 on 2025-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('data', models.CharField(max_length=200)),
            ],
        ),
    ]
