# Generated by Django 5.1.7 on 2025-03-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_complaint_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='course',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='roll',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
